---
- name: restart_influxdb
  service:
    name: influxdb
    state: restarted

- name: enable_influxdb
  service:
    name: influxdb
    enabled: yes

- name: start_influxdb
  service:
    name: influxdb
    state: started

- name: enable_chronograf
  service:
    name: chronograf
    enabled: yes

- name: start_chronograf
  service:
    name: chronograf
    state: started